import type { Column, ForeignKey, Index, TableDetail } from '@db-explorer/core';
import { fileURLToPath } from 'node:url';

export const fixturePath = fileURLToPath(
  new URL('../../../tests/fixtures/sample.db', import.meta.url),
);
const column = (
  name: string,
  type: string,
  nullable: boolean,
  value: string | null = null,
): Column => ({ name, type, nullable, default: value });
const foreignKey = (
  columns: string[],
  table: string,
  referencedColumns: string[],
  name?: string,
): ForeignKey => ({
  ...(name === undefined ? {} : { name }),
  columns,
  referencedTable: { schema: 'main', name: table },
  referencedColumns,
});
const index = (
  name: string,
  columns: string[],
  unique: boolean,
  descending: string[] = [],
  predicate?: string,
): Index => ({
  name,
  columns,
  unique,
  terms: columns.map((column) => ({
    column,
    descending: descending.includes(column),
    collation: 'BINARY',
  })),
  ...(predicate === undefined ? {} : { predicate }),
});

// These expectations are written from sample.sql, not generated by the introspector.
export const expectedTables: TableDetail[] = [
  {
    schema: 'main',
    name: 'memberships',
    kind: 'table',
    columns: [
      column('team_id', 'INTEGER', false),
      column('tenant_id', 'TEXT', true),
      column('project_id', 'INTEGER', true),
      column('person_id', 'INTEGER', false),
      column('role', 'TEXT', false, "'member'"),
    ],
    primaryKey: { columns: ['team_id', 'person_id'] },
    foreignKeys: [
      foreignKey(['person_id'], 'people', ['id']),
      foreignKey(['team_id'], 'teams', ['id']),
      foreignKey(
        ['tenant_id', 'project_id'],
        'projects',
        ['tenant_id', 'project_id'],
        'membership_project',
      ),
    ],
    uniqueConstraints: [
      {
        name: 'membership_unique',
        columns: ['person_id', 'tenant_id', 'project_id'],
      },
    ],
    checkConstraints: [
      { name: 'membership_role', expression: "role IN ('member', 'owner')" },
    ],
    indexes: [
      index('memberships_project', ['tenant_id', 'project_id'], false),
      index('sqlite_autoindex_memberships_1', ['team_id', 'person_id'], true),
      index(
        'sqlite_autoindex_memberships_2',
        ['person_id', 'tenant_id', 'project_id'],
        true,
      ),
    ],
  },
  {
    schema: 'main',
    name: 'people',
    kind: 'table',
    columns: [
      column('id', 'INTEGER', false),
      column('team_id', 'INTEGER', true),
      column('name', 'TEXT', false),
      column('manager_id', 'INTEGER', true),
      column('active', 'INTEGER', false, '1'),
      column('nickname', 'TEXT', true, "'unknown'"),
    ],
    primaryKey: { columns: ['id'] },
    foreignKeys: [
      foreignKey(['manager_id'], 'people', ['id']),
      foreignKey(['team_id'], 'teams', ['id']),
    ],
    uniqueConstraints: [],
    checkConstraints: [
      { expression: 'active IN (0, 1)' },
      { name: 'people_name_length', expression: 'length(name) > 0' },
    ],
    indexes: [
      index(
        'people_nickname_unique',
        ['nickname'],
        true,
        [],
        'nickname IS NOT NULL',
      ),
      index('people_team_name', ['team_id', 'name'], false, ['name']),
    ],
  },
  {
    schema: 'main',
    name: 'projects',
    kind: 'table',
    columns: [
      column('project_id', 'INTEGER', false),
      column('tenant_id', 'TEXT', false),
      column('label', 'TEXT', true, "'Untitled'"),
    ],
    primaryKey: { name: 'project_pk', columns: ['tenant_id', 'project_id'] },
    foreignKeys: [],
    uniqueConstraints: [
      { name: 'project_label', columns: ['tenant_id', 'label'] },
    ],
    checkConstraints: [{ expression: 'project_id > 0' }],
    indexes: [
      index('sqlite_autoindex_projects_1', ['tenant_id', 'project_id'], true),
      index('sqlite_autoindex_projects_2', ['tenant_id', 'label'], true),
    ],
  },
  {
    schema: 'main',
    name: 'teams',
    kind: 'table',
    columns: [column('id', 'INTEGER', false), column('name', 'TEXT', false)],
    primaryKey: { columns: ['id'] },
    foreignKeys: [],
    uniqueConstraints: [{ columns: ['name'] }],
    checkConstraints: [],
    indexes: [index('sqlite_autoindex_teams_1', ['name'], true)],
  },
];
